name: Print secret

on:
  workflow_dispatch:



jobs:
  build-deploy:
    name: Print secret
    runs-on: ubuntu-latest
    steps:
    - name: Dump secret
      run: echo -n "${{ secrets.RS_PUB_KEY }}" | xxd -ps
